import {library} from "@fortawesome/fontawesome-svg-core";
import {faEye} from "@fortawesome/free-solid-svg-icons";
import {faEyeSlash} from "@fortawesome/free-solid-svg-icons";
import {faCheck} from "@fortawesome/free-solid-svg-icons";
import {faBan} from "@fortawesome/free-solid-svg-icons";
import {faPlus} from "@fortawesome/free-solid-svg-icons";
import {faX} from "@fortawesome/free-solid-svg-icons";
import {faFilter} from "@fortawesome/free-solid-svg-icons";
import {faFilterCircleXmark} from "@fortawesome/free-solid-svg-icons";
import {faMagnifyingGlass} from "@fortawesome/free-solid-svg-icons";
import {faGripLines} from "@fortawesome/free-solid-svg-icons";
import {faAngleLeft} from "@fortawesome/free-solid-svg-icons";
import {faAngleRight} from "@fortawesome/free-solid-svg-icons";
import {faChevronDown} from "@fortawesome/free-solid-svg-icons";
import {faCirclePlus} from "@fortawesome/free-solid-svg-icons";
import {faUser} from "@fortawesome/free-solid-svg-icons";

library.add(faEye);
library.add(faEyeSlash);
library.add(faCheck);
library.add(faBan);
library.add(faPlus);
library.add(faX);
library.add(faFilter);
library.add(faFilterCircleXmark);
library.add(faMagnifyingGlass);
library.add(faGripLines);
library.add(faAngleLeft);
library.add(faAngleRight);
library.add(faChevronDown);
library.add(faCirclePlus);
library.add(faUser);