import {library} from "@fortawesome/fontawesome-svg-core";
import {
    faAngleLeft,
    faAngleRight,
    faArrowRightFromBracket,
    faBan,
    faBookBookmark,
    faBookmark,
    faBookOpen,
    faCheck,
    faChevronDown,
    faCirclePlus,
    faClockRotateLeft,
    faEllipsisV,
    faEye,
    faEyeSlash,
    faFilter,
    faFilterCircleXmark,
    faGear,
    faGripLines,
    faMagnifyingGlass,
    faPen,
    faPlus,
    faRectangleList,
    faSquareXmark,
    faUpload,
    faUser,
    faX
} from "@fortawesome/free-solid-svg-icons";
import {faBookmark as faBookmarkRegular} from "@fortawesome/free-regular-svg-icons";

library.add(
    faEye,
    faEyeSlash,
    faCheck,
    faBan,
    faPlus,
    faX,
    faFilter,
    faFilterCircleXmark,
    faMagnifyingGlass,
    faGripLines,
    faAngleLeft,
    faAngleRight,
    faChevronDown,
    faCirclePlus,
    faUser,
    faGear,
    faArrowRightFromBracket,
    faUpload,
    faEllipsisV,
    faPen,
    faBookmark,
    faBookmarkRegular,
    faBookBookmark,
    faSquareXmark,
    faClockRotateLeft,
    faRectangleList)